# Generated by Django 4.2.11 on 2024-10-10 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uom', models.CharField(choices=[('pump', 'Pump'), ('tbs', 'Tablespoon'), ('wedge', 'Wedge'), ('single', 'Single'), ('pinch', 'Pinch')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('flavor_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flavors.flavorgroup')),
            ],
        ),
    ]
