# Generated by Django 4.2.11 on 2024-06-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='uom',
            field=models.CharField(choices=[('pump', 'Pump'), ('tbs', 'Tablespoon'), ('ea', 'Each')], default='ea', max_length=10),
            preserve_default=False,
        ),
    ]
