# Generated by Django 5.1.2 on 2025-02-12 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='flavor_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavors', to='flavors.flavorgroup'),
        ),
    ]
