# Generated by Django 4.2.11 on 2024-06-20 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0002_flavor_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uom', models.CharField(choices=[('pump', 'Pump'), ('tbs', 'Tablespoon'), ('ea', 'Each')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='flavor',
            name='uom',
        ),
        migrations.AddField(
            model_name='flavor',
            name='flavor_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flavors.flavorgroup'),
            preserve_default=False,
        ),
    ]
