# Generated by Django 4.2.11 on 2024-06-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0003_flavorgroup_remove_flavor_uom_flavor_flavor_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavorgroup',
            name='uom',
            field=models.CharField(choices=[('pump', 'Pump'), ('tbs', 'Tablespoon'), ('wedge', 'Wedge')], max_length=10),
        ),
    ]
