# Generated by Django 4.2.11 on 2024-06-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0004_alter_flavorgroup_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavorgroup',
            name='uom',
            field=models.CharField(choices=[('pump', 'Pump'), ('tbs', 'Tablespoon'), ('wedge', 'Wedge'), ('single', 'Singles')], max_length=10),
        ),
    ]
