# Generated by Django 5.1.2 on 2026-04-03 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('unit_size', models.PositiveSmallIntegerField()),
                ('uom', models.CharField(choices=[('ct', 'Count'), ('oz', 'Ounce'), ('gal', 'Gallon'), ('mL', 'Milliliter'), ('L', 'Liter'), ('QT', 'Quart')], max_length=50)),
                ('reorder_point', models.PositiveIntegerField()),
                ('order_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_count', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorycategory')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('received_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
            ],
        ),
    ]
