# Generated by Django 5.1.2 on 2026-05-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
