# Generated by Django 4.2.11 on 2024-06-12 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sodas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soda',
            name='zero_sugar',
        ),
    ]
