# Generated by Django 4.2.11 on 2024-06-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
