# Generated by Django 5.1.2 on 2026-07-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cup",
            name="size",
            field=models.CharField(
                choices=[("16", "16 oz"), ("24", "24 oz"), ("32", "32 oz")],
                max_length=10,
            ),
        ),
    ]
