# Generated by Django 5.1.2 on 2026-07-19 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cups", "0002_alter_cup_size"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cup",
            options={
                "ordering": ["size"],
                "verbose_name": "Cup",
                "verbose_name_plural": "Cups",
            },
        ),
    ]
