# Generated by Django 5.1.2 on 2025-07-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='version',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
