# Generated by Django 4.2.11 on 2024-06-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemflavor',
            name='uom',
        ),
    ]
