# Generated by Django 5.1.2 on 2024-12-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitedtimepromotion',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
