# Generated by Django 5.1.2 on 2025-03-05 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0002_limitedtimepromotion_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the menu_item of a 16 oz drink, not including the price of the cup', max_digits=5)),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='menuitems.menuitem')),
            ],
        ),
    ]
