# Generated by Django 5.1.2 on 2025-10-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0003_menuitemprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
