# Generated by Django 4.2.11 on 2024-10-11 06:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flavors', '0001_initial'),
        ('cups', '0001_initial'),
        ('locations', '0001_initial'),
        ('sodas', '0001_initial'),
        ('menuitems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_orders', to='sodas.soda')),
            ],
        ),
        migrations.CreateModel(
            name='CustomOrderFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_order_flavors', to='flavors.flavor')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemCustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_orders', to='menuitems.menuitem')),
                ('soda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_custom_orders', to='sodas.soda')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_in_progress', models.BooleanField(default=False)),
                ('collected_by', models.ForeignKey(help_text='The user who collected the order payment', on_delete=django.db.models.deletion.PROTECT, related_name='orders_collected', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='locations.location')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_sugar', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('is_prepared', models.BooleanField(default=False)),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cups.cup')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPaidAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paid_amount', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemMenuItemCustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_custom_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_custom_order_order_items', to='orders.menuitemcustomorder')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_custom_order', to='orders.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_order_items', to='menuitems.menuitem')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='orders.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemCustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_order_order_items', to='orders.customorder')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_order', to='orders.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.discount')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.ordername'),
        ),
        migrations.CreateModel(
            name='DiscountPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.discount')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountPercentOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_off', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('discount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.discount')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCupSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cups.cup')),
                ('discount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.discount')),
            ],
        ),
        migrations.CreateModel(
            name='CustomOrderFlavorMenuItemCustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_order_flavor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_order_flavor_menu_item_custom_order', to='orders.customorderflavor')),
                ('menu_item_custom_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_custom_order_custom_order_flavors', to='orders.menuitemcustomorder')),
            ],
        ),
        migrations.CreateModel(
            name='CustomOrderFlavorCustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_order_custom_order_flavors', to='orders.customorder')),
                ('custom_order_flavor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_order_flavor_custom_order', to='orders.customorderflavor')),
            ],
        ),
    ]
