# Generated by Django 4.2.11 on 2024-09-11 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flavors', '0002_flavorgroup_price'),
        ('menuitems', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('cups', '0002_cup_conversion_factor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
        ('sodas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_prepared', models.BooleanField(default=False)),
                ('collected_by', models.ForeignKey(help_text='The user who collected the order payment', on_delete=django.db.models.deletion.PROTECT, related_name='orders_collected', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='locations.location')),
            ],
        ),
        migrations.CreateModel(
            name='OrderName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zero_sugar', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('is_prepared', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cups.cup')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.ordername'),
        ),
        migrations.AddField(
            model_name='order',
            name='prepared_by',
            field=models.ForeignKey(help_text='The user who prepared the items in the order', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_prepared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MenuItemCustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_orders', to='menuitems.menuitem')),
                ('soda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_custom_orders', to='sodas.soda')),
            ],
        ),
        migrations.CreateModel(
            name='CustomOrderFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_order_flavors', to='flavors.flavor')),
            ],
        ),
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_orders', to='sodas.soda')),
            ],
        ),
    ]
