# Generated by Django 4.2.11 on 2024-09-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prepared_by',
        ),
        migrations.AddField(
            model_name='order',
            name='is_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
