# Generated by Django 5.1.2 on 2024-11-07 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_prepared',
        ),
    ]
