# Generated by Django 4.2.11 on 2024-09-25 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0001_initial'),
        ('orders', '0002_remove_order_prepared_by_order_is_in_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_order_items', to='menuitems.menuitem')),
            ],
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='zero_sugar',
            new_name='low_sugar',
        ),
        migrations.RemoveField(
            model_name='customorderflavor',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='customorderflavor',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='object_id',
        ),
        migrations.CreateModel(
            name='OrderItemMenuItemCustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_custom_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_custom_order_order_items', to='orders.orderitemmenuitem')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_menu_item_custom_orders', to='orders.orderitem')),
            ],
        ),
        migrations.AddField(
            model_name='orderitemmenuitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_menu_items', to='orders.orderitem'),
        ),
        migrations.CreateModel(
            name='OrderItemCustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_order_order_items', to='orders.customorder')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_custom_orders', to='orders.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='CustomOrderFlavorMenuItemCustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_order_flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_order_flavor_menu_item_custom_orders', to='orders.customorderflavor')),
                ('menu_item_custom_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_custom_order_custom_order_flavors', to='orders.menuitemcustomorder')),
            ],
        ),
        migrations.CreateModel(
            name='CustomOrderFlavorCustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_order_custom_order_flavors', to='orders.customorder')),
                ('custom_order_flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_order_flavor_custom_orders', to='orders.customorderflavor')),
            ],
        ),
    ]
