# Generated by Django 5.1.2 on 2025-04-26 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_is_prepared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.ordername'),
        ),
        migrations.AlterField(
            model_name='ordername',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
