# Generated by Django 4.2.11 on 2024-09-26 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitemmenuitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorderflavorcustomorder',
            name='custom_order_flavor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_order_flavor_custom_order', to='orders.customorderflavor'),
        ),
        migrations.AlterField(
            model_name='customorderflavormenuitemcustomorder',
            name='custom_order_flavor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_order_flavor_menu_item_custom_order', to='orders.customorderflavor'),
        ),
        migrations.AlterField(
            model_name='orderitemcustomorder',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_order', to='orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='orderitemmenuitem',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='orderitemmenuitemcustomorder',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_custom_order', to='orders.orderitem'),
        ),
    ]
