# Generated by Django 5.1.2 on 2026-07-19 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_order_name_alter_ordername_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customorderflavor",
            name="quantity",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
