# Generated by Django 4.2.11 on 2024-09-26 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_customorderflavorcustomorder_custom_order_flavor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmenuitemcustomorder',
            name='menu_item_custom_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_custom_order_order_items', to='orders.menuitemcustomorder'),
        ),
    ]
