# Generated by Django 4.2.11 on 2024-09-26 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitemmenuitemcustomorder_menu_item_custom_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_prepared',
            new_name='is_complete',
        ),
    ]
