# Generated by Django 4.2.11 on 2024-07-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
