# Generated by Django 4.2.11 on 2024-08-01 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0002_flavorgroup_price'),
        ('sodas', '0001_initial'),
        ('orders', '0006_alter_orderitem_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_orders', to='sodas.soda')),
            ],
        ),
        migrations.CreateModel(
            name='CustomOrderFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('custom_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_flavors', to='orders.customorder')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_order_flavors', to='flavors.flavor')),
            ],
        ),
    ]
