# Generated by Django 4.2.11 on 2024-08-06 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_customorder_customorderflavor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed_by',
            new_name='collected_by',
        ),
    ]
