# Generated by Django 4.2.11 on 2024-10-08 04:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discount',
        ),
        migrations.CreateModel(
            name='DiscountPercentOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_off', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.discount')),
            ],
        ),
    ]
