# Generated by Django 4.2.11 on 2024-10-08 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_discount_discount_discountpercentoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountpercentoff',
            name='discount',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.discount'),
        ),
        migrations.CreateModel(
            name='DiscountPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.discount')),
            ],
        ),
    ]
