# Generated by Django 4.2.11 on 2024-08-06 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0008_rename_completed_by_order_collected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_prepared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='prepared_by',
            field=models.ForeignKey(default=1, help_text='The user who prepared the items in the order', on_delete=django.db.models.deletion.PROTECT, related_name='orders_prepared', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='collected_by',
            field=models.ForeignKey(help_text='The user who collected the order payment', on_delete=django.db.models.deletion.PROTECT, related_name='orders_collected', to=settings.AUTH_USER_MODEL),
        ),
    ]
