# Generated by Django 4.2.11 on 2024-08-06 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0009_order_is_prepared_order_prepared_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prepared_by',
            field=models.ForeignKey(help_text='The user who prepared the items in the order', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_prepared', to=settings.AUTH_USER_MODEL),
        ),
    ]
