# Generated by Django 4.2.11 on 2024-10-08 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cups', '0002_cup_conversion_factor'),
        ('orders', '0009_alter_discountpercentoff_discount_discountprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCupSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cups.cup')),
                ('discount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.discount')),
            ],
        ),
    ]
