# Generated by Django 4.2.11 on 2024-10-10 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid_amount',
        ),
        migrations.CreateModel(
            name='OrderPaidAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paid_amount', to='orders.order')),
            ],
        ),
    ]
