# Generated by Django 4.2.11 on 2024-08-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_order_discount_order_order_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
